name: mental
recipe: drupal9
config:
  php: '8.2'
  webroot: web

# Services
services:
  database:
    portforward: 58077
    creds:
      user: drupal9
      password: drupal9
      database: drupal9
  mental-phpmyadmin:
    type: phpmyadmin

# Proxy
proxy:
  mental-phpmyadmin:
    - mental-phpmyadmin.lndo.site
