name: mhanational
recipe: drupal9
config:
  php: '8.2'
  webroot: web

# Services
services:
  database:
    portforward: 58777
    creds:
      user: drupal9
      password: drupal9
      database: drupal9
  mhanational-phpmyadmin:
    type: phpmyadmin

# Proxy
proxy:
  mhanational-phpmyadmin:
    - mhanational-phpmyadmin.lndo.site
