name: Charts Blocks
type: module
description: Create Charts blocks without the need for Views.
core_version_requirement: ^9.2 || ^10
package: Charts
dependencies:
  - drupal:charts

# Information added by Drupal.org packaging script on 2024-12-02
version: '5.0.17'
project: 'charts'
datestamp: 1733170558
