action.configuration.content_bulk_export:
  type: action_configuration_default
  label: 'Export content'

single_content_sync.settings:
  type: config_object
  label: 'Single Content Sync settings'
  mapping:
    allowed_entity_types:
      type: sequence
      sequence:
        type: string
        label: 'Allowed entity types to export'
