<?php

/**
 * @file
 * Install, update and uninstall functions for this module.
 */

declare(strict_types=1);

/**
 * Add backwards-compatible configuration for new account validation settings.
 *
 * The new default settings of created->true updated->false would cause a change
 * in functionality to existing installations. This update sets both values to
 * true.
 */
function advanced_email_validation_update_10101() {
  $config = \Drupal::configFactory()->getEditable('advanced_email_validation.settings');
  $config->set('validate_account_on', [
    'created' => TRUE,
    'updated' => TRUE,
  ])->save();
}
