name: 'Google Charts'
type: module
description: 'Charts module integration with Google Charts.'
package: Charts
core_version_requirement: ^9.2 || ^10
dependencies:
  - 'charts:charts'

# Information added by Drupal.org packaging script on 2025-01-08
version: '5.0.18'
project: 'charts'
datestamp: 1736346720
